const seed=[
{id:1,title:'VM에서 외부 네트워크 Ping 실패',category:'Network',status:'해결 완료',symptom:'가상머신에서 게이트웨이와 외부 IP로 Ping이 전달되지 않음',cause:'네트워크 인터페이스의 게이트웨이 설정이 누락되어 기본 경로가 생성되지 않음',solution:'인터페이스 설정에 게이트웨이를 추가하고 route 정보를 다시 확인한 뒤 Ping 테스트'},
{id:2,title:'GNS3 가상 장비 메모리 부족',category:'Virtualization',status:'해결 완료',symptom:'가상 네트워크 장비 시작 시 RAM 부족 메시지와 함께 실행 중단',cause:'GNS3 VM에 할당된 메모리보다 실행 장비의 요구 메모리가 큼',solution:'GNS3 VM 메모리 할당량과 동시 실행 장비 수를 조정하고 재실행'},
{id:3,title:'Linux 서비스 자동 시작 실패',category:'Linux',status:'해결 중',symptom:'재부팅 후 필요한 서비스가 자동으로 실행되지 않음',cause:'서비스 enable 상태와 의존성 설정을 점검 중',solution:'systemctl status 및 journal 로그를 확인해 실패 원인을 추적 중'}];
let logs=JSON.parse(localStorage.getItem('itTroubleLogs')||'null')||seed;
const $=id=>document.getElementById(id); const save=()=>localStorage.setItem('itTroubleLogs',JSON.stringify(logs));
function render(){let q=$('search').value.toLowerCase(),cat=$('category').value,st=$('status').value;let list=logs.filter(x=>(cat==='all'||x.category===cat)&&(st==='all'||x.status===st)&&[x.title,x.symptom,x.cause,x.solution].join(' ').toLowerCase().includes(q));$('cards').innerHTML=list.map(x=>`<article class="card"><div class="card-top"><span class="tag">${esc(x.category)}</span><span class="status ${x.status==='해결 완료'?'solved':''}">${x.status}</span></div><h3>${esc(x.title)}</h3><dl><dt>증상</dt><dd>${esc(x.symptom)}</dd><dt>원인</dt><dd>${esc(x.cause||'아직 기록되지 않음')}</dd><dt>해결 방법</dt><dd>${esc(x.solution||'아직 기록되지 않음')}</dd></dl><div class="card-actions"><button onclick="editLog(${x.id})">수정</button><button class="danger" onclick="deleteLog(${x.id})">삭제</button></div></article>`).join('');$('empty').hidden=list.length>0;$('total').textContent=logs.length;$('solved').textContent=logs.filter(x=>x.status==='해결 완료').length;$('open').textContent=logs.filter(x=>x.status==='해결 중').length}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function openForm(x){$('editId').value=x?.id||'';$('modalTitle').textContent=x?'장애 기록 수정':'새 장애 기록';$('title').value=x?.title||'';$('formCategory').value=x?.category||'Network';$('formStatus').value=x?.status||'해결 중';$('symptom').value=x?.symptom||'';$('cause').value=x?.cause||'';$('solution').value=x?.solution||'';$('modal').showModal()}
window.editLog=id=>openForm(logs.find(x=>x.id===id));window.deleteLog=id=>{if(confirm('이 기록을 삭제할까요?')){logs=logs.filter(x=>x.id!==id);save();render()}};
$('addBtn').onclick=()=>openForm();$('closeBtn').onclick=$('cancelBtn').onclick=()=>$('modal').close();$('form').onsubmit=e=>{e.preventDefault();let id=+$('editId').value;let item={id:id||Date.now(),title:$('title').value.trim(),category:$('formCategory').value,status:$('formStatus').value,symptom:$('symptom').value.trim(),cause:$('cause').value.trim(),solution:$('solution').value.trim()};if(id)logs=logs.map(x=>x.id===id?item:x);else logs.unshift(item);save();$('modal').close();render()};['search','category','status'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));render();
