const seed=[
{id:1,title:'VM에서 외부 네트워크 Ping 실패',category:'Network',status:'해결 완료',priority:'높음',symptom:'가상머신에서 게이트웨이와 외부 IP로 Ping이 전달되지 않음',cause:'네트워크 인터페이스의 게이트웨이 설정이 누락되어 기본 경로가 생성되지 않음',solution:'인터페이스 설정에 게이트웨이를 추가하고 route 정보를 다시 확인한 뒤 Ping 테스트',checks:{retest:true,document:true,backup:false}},
{id:2,title:'GNS3 가상 장비 메모리 부족',category:'Virtualization',status:'해결 완료',priority:'보통',symptom:'가상 네트워크 장비 시작 시 RAM 부족 메시지와 함께 실행 중단',cause:'GNS3 VM에 할당된 메모리보다 실행 장비의 요구 메모리가 큼',solution:'GNS3 VM 메모리 할당량과 동시 실행 장비 수를 조정하고 재실행',checks:{retest:true,document:false,backup:false}},
{id:3,title:'Linux 서비스 자동 시작 실패',category:'Linux',status:'해결 중',priority:'높음',symptom:'재부팅 후 필요한 서비스가 자동으로 실행되지 않음',cause:'서비스 enable 상태와 의존성 설정을 점검 중',solution:'systemctl status 및 journal 로그를 확인해 실패 원인을 추적 중',checks:{retest:false,document:false,backup:false}}];
let logs=JSON.parse(localStorage.getItem('itTroubleLogs')||'null')||seed;
logs=logs.map(x=>({...x,priority:x.priority||'보통',checks:x.checks||{retest:false,document:false,backup:false}}));
const $=id=>document.getElementById(id); const save=()=>localStorage.setItem('itTroubleLogs',JSON.stringify(logs));
const checkLabels={retest:'동일 환경에서 재테스트',document:'설정 변경 내용 문서화',backup:'설정 또는 구성 백업'};
function render(){let q=$('search').value.toLowerCase(),cat=$('category').value,st=$('status').value,pri=$('priority').value;let list=logs.filter(x=>(cat==='all'||x.category===cat)&&(st==='all'||x.status===st)&&(pri==='all'||x.priority===pri)&&[x.title,x.symptom,x.cause,x.solution].join(' ').toLowerCase().includes(q));$('cards').innerHTML=list.map(x=>{let checks=Object.entries(x.checks||{}).map(([k,v])=>`<li class="${v?'done':''}">${v?'✓':'○'} ${checkLabels[k]}</li>`).join('');return `<article class="card"><div class="card-top"><div class="badges"><span class="tag">${esc(x.category)}</span><span class="priority p-${esc(x.priority)}">${esc(x.priority)}</span></div><span class="status ${x.status==='해결 완료'?'solved':''}">${x.status}</span></div><h3>${esc(x.title)}</h3><dl><dt>증상</dt><dd>${esc(x.symptom)}</dd><dt>원인</dt><dd>${esc(x.cause||'아직 기록되지 않음')}</dd><dt>해결 방법</dt><dd>${esc(x.solution||'아직 기록되지 않음')}</dd></dl><div class="prevention"><b>재발 방지</b><ul>${checks}</ul></div><div class="card-actions"><button onclick="exportReport(${x.id})">리포트 내보내기</button><button onclick="editLog(${x.id})">수정</button><button class="danger" onclick="deleteLog(${x.id})">삭제</button></div></article>`}).join('');$('empty').hidden=list.length>0;$('total').textContent=logs.length;$('solved').textContent=logs.filter(x=>x.status==='해결 완료').length;$('open').textContent=logs.filter(x=>x.status==='해결 중').length}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function openForm(x){$('editId').value=x?.id||'';$('modalTitle').textContent=x?'장애 기록 수정':'새 장애 기록';$('title').value=x?.title||'';$('formCategory').value=x?.category||'Network';$('formStatus').value=x?.status||'해결 중';$('formPriority').value=x?.priority||'보통';$('symptom').value=x?.symptom||'';$('cause').value=x?.cause||'';$('solution').value=x?.solution||'';$('checkRetest').checked=!!x?.checks?.retest;$('checkDocument').checked=!!x?.checks?.document;$('checkBackup').checked=!!x?.checks?.backup;$('modal').showModal()}
window.editLog=id=>openForm(logs.find(x=>x.id===id));
window.exportReport=id=>{const x=logs.find(v=>v.id===id);if(!x)return;const checks=Object.entries(x.checks||{}).map(([k,v])=>`[${v?'완료':'미완료'}] ${checkLabels[k]}`).join('\n');const report=`IT 실습 장애 해결 리포트\n\n장애 제목: ${x.title}\n분야: ${x.category}\n중요도: ${x.priority}\n상태: ${x.status}\n\n증상\n${x.symptom||'기록 없음'}\n\n원인\n${x.cause||'기록 없음'}\n\n해결 방법\n${x.solution||'기록 없음'}\n\n재발 방지 체크리스트\n${checks}`;const blob=new Blob(['\ufeff'+report],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`IT_장애리포트_${x.title.replace(/[\\/:*?"<>|]/g,'_')}.txt`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
window.deleteLog=id=>{if(confirm('이 기록을 삭제할까요?')){logs=logs.filter(x=>x.id!==id);save();render()}};
$('addBtn').onclick=()=>openForm();$('closeBtn').onclick=$('cancelBtn').onclick=()=>$('modal').close();$('form').onsubmit=e=>{e.preventDefault();let id=+$('editId').value;let item={id:id||Date.now(),title:$('title').value.trim(),category:$('formCategory').value,status:$('formStatus').value,priority:$('formPriority').value,symptom:$('symptom').value.trim(),cause:$('cause').value.trim(),solution:$('solution').value.trim(),checks:{retest:$('checkRetest').checked,document:$('checkDocument').checked,backup:$('checkBackup').checked}};if(id)logs=logs.map(x=>x.id===id?item:x);else logs.unshift(item);save();$('modal').close();render()};['search','category','status','priority'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));save();render();